[package]
name = "rinker"
version = "0.2.0"
edition = "2021"

[dependencies]
select = "0.6.0"
reqwest = { version = "0.11", features = ["blocking"] }

[profile.release]
opt-level = 'z'
strip = true
lto = true
codegen-units = 1